- name: Installing apache server
  hosts: linux
  become: yes
  tasks:
  - name: install apache on centos
    package:
      state: present
      update_cache: yes
      name: httpd
    when: ansible_facts['os_family'] == "RedHat"
  - name: install apache on ubuntu
    package:
      state: present
      update_cache: yes
      name: apache2
    when: ansible_facts['os_family'] == "Ubuntu"