- name: Installing nodejs and NPM
  hosts: all
  vars:
    repo_name: nodejs
    branch_name: master
  become: no
  tasks:
  - name: Installing nodejs
    package:
      name:
        - nodejs
        - npm
      state: present
      update_cache: yes
    become: yes
  - name: running shell commands
    shell: "node --version && npm --version"
    register: output
  - name: print the output of shell commands
    debug: var=output.stdout_lines 
  - name: removing app directory
    file:
      path: /opt/app
      owner: ubuntu
      group: ubuntu
      state: absent
  - name: creating app directory
    file:
      path: /opt/app
      owner: ubuntu
      group: ubuntu
      state: directory
  - name: download code
    git:
      repo: "https://github.com/kul-samples/{{ repo_name }}.git"
      dest: "/opt/app"
      version: "{{ branch_name }}"
      accept_hostkey: yes
  - name: Install packages based on package.json.
    npm:
      path: /opt/app
  - name: Start App
    command: forever start app.js
    args:
      chdir: "/opt/app"
  - name: Logs of APP
    command: foreven logs app.js
    register: output
  - name: print the output of shell commands
    debug: var=output.stdout_lines  