- name: Installing nodejs and NPM
  hosts: all
  become: no
  tasks:
  - name: Installing nodejs
    package:
      name:
        - nodejs
        - npm
      state: present
      update_cache: yes
    become: yes
  - name: running shell commands
    shell: "node --version && npm --version"
    register: output
  - name: print the output of shell commands
    debug: var=output.stdout_lines 
  - name: removing app directory
    file:
      path: /opt/app
      owner: ubuntu
      group: ubuntu
      state: absent
  - name: creating app directory
    file:
      path: /opt/app
      owner: ubuntu
      group: ubuntu
      state: directory
  - name: cloning a git repo
    git:
      repo: 'https://github.com/kul-samples/nodejs.git'
      dest: /opt/app
      update: yes