- name: Tomcat installation
  hosts: all
  become: no
  vars: 
    url_name: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.60/bin/apache-tomcat-9.0.60.tar.gz"
    connector_port: 9090
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    CATALINA_HOME: /opt/apache-tomcat-9.0.60
    CATALINA_BASE: /opt/apache-tomcat-9.0.60
    TOMCAT_USER: root
  tasks:
  - name: Install JRE
    package:
      name: default-jdk
      state: present
      update_cache: yes
    become: yes
  - name: setting up tomcat 
    get_url:
      url: "{{url_name}}"
      dest: /opt/apache-tomcat-9.0.60.tar.gz
    become: yes
    notify: 
    - untar_tomcat_tar_file
  - name: change owner for /opt
    file:
      path: /opt
      owner: ubuntu
      group: ubuntu
    become: yes
  - name: Extracting tar file
    unarchive:
      src: /opt/apache-tomcat-9.0.60.tar.gz
      dest: /opt
  - name: updating server.xml
    template: 
      src: server.xml.j2
      dest: "{{ CATALINA_HOME }}/conf/server.xml"
    notify:
       - restart_tomcat
  - name: adding tomcat init file
    template:
      src: tomcat-init.sh.j2
      dest: /etc/init.d/tomcat
      mode: "0755"
    become: yes
  - name: start tomcat
    service:
      name: tomcat
      state: started
      enabled: no
    become: yes
  handlers: # are like tasks but being on the basis of the change any task defined under tasks
  - name: untar_tomcat_tar_file
    unarchive:
      src: /opt/apache-tomcat-9.0.60.tar.gz
      dest: /opt
  - name: restart_tomcat
    service:
      name: tomcat
      state: restarted
    become: yes
    
  


